version: '3.4'

services:
  betclic.ranking.api:
    image: ${DOCKER_REGISTRY-}betclicrankingapi
    restart: always
    build:
      context: .
      dockerfile: Betclic.Ranking.API/Dockerfile
      
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"